# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_main(object):
    def setupUi(self, form_main):
        form_main.setObjectName("form_main")
        form_main.resize(622, 582)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(form_main.sizePolicy().hasHeightForWidth())
        form_main.setSizePolicy(sizePolicy)
        form_main.setMinimumSize(QtCore.QSize(0, 0))
        form_main.setMaximumSize(QtCore.QSize(999, 999))
        self.groupBox_2 = QtWidgets.QGroupBox(form_main)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 440, 621, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 621, 121))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text_log = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.text_log.setReadOnly(True)
        self.text_log.setObjectName("text_log")
        self.verticalLayout_3.addWidget(self.text_log)
        self.groupBox_3 = QtWidgets.QGroupBox(form_main)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 0, 371, 449))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 371, 421))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_parser = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.text_parser.setReadOnly(True)
        self.text_parser.setObjectName("text_parser")
        self.verticalLayout_2.addWidget(self.text_parser)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_sentence = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.line_sentence.setObjectName("line_sentence")
        self.horizontalLayout_2.addWidget(self.line_sentence)
        self.btn_recognize = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_recognize.setObjectName("btn_recognize")
        self.horizontalLayout_2.addWidget(self.btn_recognize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_2.raise_()
        self.groupBox = QtWidgets.QGroupBox(form_main)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 241, 449))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 241, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_read = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_read.setObjectName("btn_read")
        self.verticalLayout.addWidget(self.btn_read)
        self.btn_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout.addWidget(self.btn_save)
        self.text_grammar = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.text_grammar.setObjectName("text_grammar")
        self.verticalLayout.addWidget(self.text_grammar)
        self.btn_verify = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_verify.setObjectName("btn_verify")
        self.verticalLayout.addWidget(self.btn_verify)
        self.btn_parser = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_parser.setObjectName("btn_parser")
        self.verticalLayout.addWidget(self.btn_parser)
        self.verticalLayoutWidget.raise_()
        self.groupBox_2.raise_()

        self.retranslateUi(form_main)
        QtCore.QMetaObject.connectSlotsByName(form_main)

    def retranslateUi(self, form_main):
        _translate = QtCore.QCoreApplication.translate
        form_main.setWindowTitle(_translate("form_main", "Context Free Grammar Simulator"))
        self.groupBox_2.setTitle(_translate("form_main", "Log das operações"))
        self.groupBox_3.setTitle(_translate("form_main", "Parser descendente recursivo"))
        self.btn_recognize.setText(_translate("form_main", "Reconhecer sentença"))
        self.groupBox.setTitle(_translate("form_main", "Gramática livre de contexto"))
        self.btn_read.setText(_translate("form_main", "Ler de arquivo"))
        self.btn_save.setText(_translate("form_main", "Salvar em arquivo"))
        self.btn_verify.setText(_translate("form_main", "Verificar se é LL(1)"))
        self.btn_parser.setText(_translate("form_main", "Gerar parser descente recursivo"))

